import { useState, useEffect } from 'react';
import { 
  Sparkles, 
  Briefcase, 
  Download, 
  RefreshCw, 
  AlertCircle,
  CheckCircle,
  FileText,
  DollarSign,
  Calendar,
  AlertTriangle,
  Lock,
  ChevronRight
} from 'lucide-react';
import { FileItem } from '../types';

interface AIContractToolProps {
  fileItem: FileItem;
  onReset: () => void;
}

interface ContractSummary {
  riskLevel: 'Low' | 'Medium' | 'High';
  overallScore: number; // 0-100 (where 100 is high risk or maybe risk score)
  riskExplanation: string;
  coreObligations: string[];
  paymentTerms: string[];
  keyDeadlines: string[];
  riskClauses: {
    clauseName: string;
    description: string;
    severity: 'Low' | 'Medium' | 'High';
    recommendation: string;
  }[];
  mitigationSteps: string[];
}

export default function AIContractTool({ fileItem, onReset }: AIContractToolProps) {
  const [isGenerating, setIsGenerating] = useState<boolean>(true);
  const [errorMessage, setErrorMessage] = useState<string | null>(null);
  const [summary, setSummary] = useState<ContractSummary | null>(null);
  const [activeSection, setActiveSection] = useState<'overview' | 'obligations' | 'commercials' | 'risks'>('overview');

  useEffect(() => {
    analyzeContract();
  }, [fileItem.id]);

  const analyzeContract = async () => {
    setIsGenerating(true);
    setErrorMessage(null);
    setSummary(null);

    const formData = new FormData();
    formData.append('file', fileItem.file);

    try {
      const response = await fetch('/api/convert/ai-contract', {
        method: 'POST',
        body: formData
      });

      if (!response.ok) {
        const errText = await response.text();
        throw new Error(errText || 'Could not analyze contract. Please try again.');
      }

      const data = await response.json();
      if (data.success) {
        setSummary(data.summary);
      } else {
        throw new Error(data.error || 'Server failed to analyze the agreement.');
      }
    } catch (err: any) {
      console.error('Contract analysis error:', err);
      setErrorMessage(err.message || 'Failed to analyze this contract. Ensure it contains readable text.');
    } finally {
      setIsGenerating(false);
    }
  };

  const handleDownloadReport = () => {
    if (!summary) return;

    let textContent = `==================================================\n`;
    textContent += `CONTRACT RISK & OBLIGATION AUDIT REPORT\n`;
    textContent += `Document Name: ${fileItem.name}\n`;
    textContent += `Generated by PDF PRO on ${new Date().toLocaleDateString()}\n`;
    textContent += `==================================================\n\n`;

    textContent += `RISK PROFILE ASSESSMENT\n`;
    textContent += `--------------------------------------------------\n`;
    textContent += `Overall Risk Level: ${summary.riskLevel.toUpperCase()}\n`;
    textContent += `Risk Score: ${summary.overallScore}/100\n`;
    textContent += `Risk Summary: ${summary.riskExplanation}\n\n`;

    textContent += `CORE OBLIGATIONS & ACTION ITEMS\n`;
    textContent += `--------------------------------------------------\n`;
    summary.coreObligations.forEach((obl, i) => {
      textContent += `[${i + 1}] ${obl}\n`;
    });
    textContent += `\n`;

    textContent += `PAYMENT & COMMERCIAL TERMS\n`;
    textContent += `--------------------------------------------------\n`;
    summary.paymentTerms.forEach((pay, i) => {
      textContent += `• ${pay}\n`;
    });
    textContent += `\n`;

    textContent += `CRITICAL DEADLINES & MILESTONES\n`;
    textContent += `--------------------------------------------------\n`;
    summary.keyDeadlines.forEach((dl, i) => {
      textContent += `• ${dl}\n`;
    });
    textContent += `\n`;

    textContent += `IDENTIFIED RISK CLAUSES & MITIGATIONS\n`;
    textContent += `--------------------------------------------------\n`;
    summary.riskClauses.forEach((rc, i) => {
      textContent += `${i + 1}. CLAUSE: ${rc.clauseName} (${rc.severity.toUpperCase()} SEVERITY)\n`;
      textContent += `   Description: ${rc.description}\n`;
      textContent += `   Recommendation: ${rc.recommendation}\n\n`;
    });

    textContent += `RECOMMENDED MITIGATION STEPS\n`;
    textContent += `--------------------------------------------------\n`;
    summary.mitigationSteps.forEach((step, i) => {
      textContent += `[Step ${i + 1}] ${step}\n`;
    });

    textContent += `\n\n==================================================\n`;
    textContent += `CONFIDENTIALITY NOTICE: This report was processed on secure, isolated nodes.\n`;
    textContent += `All source documents and outputs are auto-purged from our system within 1 hour.\n`;
    textContent += `==================================================\n`;

    const blob = new Blob([textContent], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `${fileItem.name.replace(/\.[^/.]+$/, "")}-Risk-Audit.txt`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  const getRiskColor = (level: string) => {
    if (level === 'High') return 'text-rose-600 bg-rose-50 dark:bg-rose-950/20 border-rose-500/20';
    if (level === 'Medium') return 'text-amber-600 bg-amber-50 dark:bg-amber-950/20 border-amber-500/20';
    return 'text-emerald-600 bg-emerald-50 dark:bg-emerald-950/20 border-emerald-500/20';
  };

  return (
    <div className="bg-white dark:bg-[#12151C] border border-slate-100 dark:border-white/5 rounded-3xl overflow-hidden shadow-sm flex flex-col min-h-[580px]">
      
      {/* HEADER */}
      <div className="px-6 py-5 bg-slate-50 dark:bg-[#161920]/60 border-b border-slate-100 dark:border-white/5 flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div className="flex items-center space-x-3.5">
          <div className="p-2.5 bg-emerald-500/10 text-emerald-500 rounded-2xl shadow-sm">
            <Briefcase className="w-5 h-5 text-emerald-500" />
          </div>
          <div>
            <h4 className="font-display font-bold text-slate-800 dark:text-slate-100 text-base flex items-center gap-2">
              Contract Risk & Obligation Summarizer
              <span className="text-[10px] font-mono uppercase bg-emerald-500/10 text-emerald-600 dark:text-emerald-400 px-2 py-0.5 rounded font-bold">
                PRO BUSINESS
              </span>
            </h4>
            <p className="text-xs text-slate-400 dark:text-slate-500 max-w-sm truncate mt-0.5">
              Auditing: {fileItem.name} ({Math.round(fileItem.size / 1024)} KB)
            </p>
          </div>
        </div>

        <div className="flex items-center gap-2">
          {!isGenerating && summary && (
            <button
              onClick={handleDownloadReport}
              className="px-3.5 py-2 bg-slate-100 hover:bg-slate-200 dark:bg-white/5 dark:hover:bg-white/10 text-slate-700 dark:text-slate-200 rounded-xl text-xs font-bold flex items-center gap-1.5 transition-all cursor-pointer font-sans"
              title="Download Full Risk Audit PDF Report"
            >
              <Download className="w-4 h-4 text-emerald-500" />
              <span>Download summary report</span>
            </button>
          )}
          <button
            onClick={analyzeContract}
            disabled={isGenerating}
            className="p-2 hover:bg-slate-200 dark:hover:bg-[#161920] rounded-xl text-slate-400 hover:text-slate-600 dark:hover:text-slate-300 transition-colors cursor-pointer"
            title="Re-analyze and regenerate"
          >
            <RefreshCw className={`w-4 h-4 ${isGenerating ? 'animate-spin text-emerald-500' : ''}`} />
          </button>
          <button
            onClick={onReset}
            disabled={isGenerating}
            className="p-2 hover:bg-slate-200 dark:hover:bg-[#161920] rounded-xl text-slate-400 hover:text-slate-600 dark:hover:text-slate-300 transition-colors cursor-pointer text-xs font-semibold px-3 border border-slate-100 dark:border-white/5"
          >
            Close
          </button>
        </div>
      </div>

      {/* CONFIDENTIALITY NOTIFICATION BANNER */}
      <div className="bg-emerald-500/5 border-b border-emerald-500/10 px-6 py-2.5 flex items-center gap-2.5 text-[11px] text-emerald-600 dark:text-emerald-400/90 font-medium">
        <Lock className="w-3.5 h-3.5 text-emerald-500 shrink-0" />
        <span>
          <strong>Confidentiality Guarantee:</strong> Your uploaded documents are processed on sandbox server nodes and automatically deleted permanently within one hour.
        </span>
      </div>

      {/* GENERATING LOADING SCREEN */}
      {isGenerating && (
        <div className="flex-1 flex flex-col items-center justify-center p-8 text-center space-y-6 animate-fade-in my-12">
          <div className="relative">
            <div className="w-16 h-16 rounded-full border-4 border-emerald-500/10 border-t-emerald-500 animate-spin"></div>
            <div className="absolute inset-0 flex items-center justify-center">
              <Sparkles className="w-6 h-6 text-emerald-500 animate-pulse" />
            </div>
          </div>
          <div className="space-y-2 max-w-md">
            <h5 className="font-display font-bold text-slate-800 dark:text-slate-100 text-lg">
              Scanning Agreement & Extracting Risk Metrics...
            </h5>
            <p className="text-xs text-slate-400 leading-relaxed font-mono">
              Analyzing payment structures, indemnification clauses, governing laws, milestones, and calculating risk liability indicators using our Secure AI...
            </p>
          </div>
        </div>
      )}

      {/* ERROR SCREEN */}
      {!isGenerating && errorMessage && (
        <div className="flex-1 flex flex-col items-center justify-center p-8 text-center space-y-4 my-12">
          <div className="p-4 bg-rose-500/10 text-rose-500 rounded-full">
            <AlertCircle className="w-8 h-8" />
          </div>
          <div className="space-y-1 max-w-sm">
            <h5 className="font-display font-bold text-slate-800 dark:text-slate-100 text-base">
              Failed to Analyze Contract
            </h5>
            <p className="text-xs text-slate-400 leading-relaxed">
              {errorMessage}
            </p>
          </div>
          <button
            onClick={analyzeContract}
            className="px-4 py-2 bg-emerald-600 hover:bg-emerald-500 text-white text-xs font-bold rounded-xl shadow-md cursor-pointer transition-all font-sans"
          >
            Retry Analysis
          </button>
        </div>
      )}

      {/* COMPLETED VIEW */}
      {!isGenerating && summary && (
        <div className="flex-1 flex flex-col">
          
          {/* TAB BAR */}
          <div className="px-6 bg-slate-50/50 dark:bg-[#161920]/20 border-b border-slate-100 dark:border-white/5 flex space-x-1.5 p-2">
            <button
              onClick={() => setActiveSection('overview')}
              className={`px-4 py-2 text-xs font-bold rounded-xl transition-all cursor-pointer flex items-center gap-1.5 ${
                activeSection === 'overview'
                  ? 'bg-emerald-600 text-white shadow-sm shadow-emerald-500/10'
                  : 'text-slate-500 hover:text-slate-800 dark:text-slate-400 dark:hover:text-slate-200 hover:bg-slate-100 dark:hover:bg-white/5'
              }`}
            >
              <FileText className="w-3.5 h-3.5" />
              Overview & Score
            </button>
            <button
              onClick={() => setActiveSection('obligations')}
              className={`px-4 py-2 text-xs font-bold rounded-xl transition-all cursor-pointer flex items-center gap-1.5 ${
                activeSection === 'obligations'
                  ? 'bg-emerald-600 text-white shadow-sm shadow-emerald-500/10'
                  : 'text-slate-500 hover:text-slate-800 dark:text-slate-400 dark:hover:text-slate-200 hover:bg-slate-100 dark:hover:bg-white/5'
              }`}
            >
              <CheckCircle className="w-3.5 h-3.5" />
              Core Obligations
            </button>
            <button
              onClick={() => setActiveSection('commercials')}
              className={`px-4 py-2 text-xs font-bold rounded-xl transition-all cursor-pointer flex items-center gap-1.5 ${
                activeSection === 'commercials'
                  ? 'bg-emerald-600 text-white shadow-sm shadow-emerald-500/10'
                  : 'text-slate-500 hover:text-slate-800 dark:text-slate-400 dark:hover:text-slate-200 hover:bg-slate-100 dark:hover:bg-white/5'
              }`}
            >
              <DollarSign className="w-3.5 h-3.5" />
              Commercial terms
            </button>
            <button
              onClick={() => setActiveSection('risks')}
              className={`px-4 py-2 text-xs font-bold rounded-xl transition-all cursor-pointer flex items-center gap-1.5 ${
                activeSection === 'risks'
                  ? 'bg-emerald-600 text-white shadow-sm shadow-emerald-500/10'
                  : 'text-slate-500 hover:text-slate-800 dark:text-slate-400 dark:hover:text-slate-200 hover:bg-slate-100 dark:hover:bg-white/5'
              }`}
            >
              <AlertTriangle className="w-3.5 h-3.5" />
              Risk Clauses
              <span className="text-[9px] px-1.5 py-0.5 bg-white/20 text-white rounded font-mono font-bold">
                {summary.riskClauses.length}
              </span>
            </button>
          </div>

          {/* TAB PANEL CONTENTS */}
          <div className="flex-1 p-6 overflow-y-auto">
            
            {/* OVERVIEW PANEL */}
            {activeSection === 'overview' && (
              <div className="space-y-6 animate-fade-in">
                {/* Score & Risk Level Metric */}
                <div className="grid grid-cols-1 md:grid-cols-3 gap-5">
                  <div className="p-5 rounded-2xl bg-slate-50 dark:bg-[#161920]/60 border border-slate-100 dark:border-white/5 flex flex-col items-center justify-center text-center space-y-2">
                    <span className="text-[10px] font-mono text-slate-400 dark:text-slate-500 uppercase tracking-widest font-bold">Risk Level</span>
                    <span className={`px-4 py-1.5 rounded-full text-sm font-black border uppercase tracking-wider ${getRiskColor(summary.riskLevel)}`}>
                      {summary.riskLevel} Risk
                    </span>
                  </div>

                  <div className="p-5 rounded-2xl bg-slate-50 dark:bg-[#161920]/60 border border-slate-100 dark:border-white/5 flex flex-col items-center justify-center text-center space-y-1">
                    <span className="text-[10px] font-mono text-slate-400 dark:text-slate-500 uppercase tracking-widest font-bold">Risk Exposure Score</span>
                    <span className="text-3xl font-black text-slate-800 dark:text-slate-100 font-mono">
                      {summary.overallScore} <span className="text-slate-400 font-normal text-lg">/ 100</span>
                    </span>
                    <div className="w-full bg-slate-200 dark:bg-slate-800 h-1.5 rounded-full overflow-hidden max-w-[120px] mt-1">
                      <div 
                        className={`h-full ${
                          summary.riskLevel === 'High' ? 'bg-rose-500' : summary.riskLevel === 'Medium' ? 'bg-amber-500' : 'bg-emerald-500'
                        }`}
                        style={{ width: `${summary.overallScore}%` }}
                      ></div>
                    </div>
                  </div>

                  <div className="p-5 rounded-2xl bg-slate-50 dark:bg-[#161920]/60 border border-slate-100 dark:border-white/5 flex flex-col items-center justify-center text-center space-y-1">
                    <span className="text-[10px] font-mono text-slate-400 dark:text-slate-500 uppercase tracking-widest font-bold">Deadlines Located</span>
                    <span className="text-2xl font-bold text-emerald-500 flex items-center gap-1 font-mono">
                      <Calendar className="w-5 h-5 text-emerald-500" />
                      {summary.keyDeadlines.length}
                    </span>
                    <span className="text-[10px] text-slate-400">Critical milestones detected</span>
                  </div>
                </div>

                {/* Risk Explanation text */}
                <div className="p-5 rounded-2xl border border-slate-100 dark:border-white/5 bg-slate-50/50 dark:bg-[#12151C]/40 space-y-2">
                  <h5 className="text-xs font-bold text-slate-800 dark:text-slate-100 flex items-center gap-1.5 font-mono uppercase tracking-wider">
                    🔍 Executive Risk Profile Summary
                  </h5>
                  <p className="text-xs text-slate-600 dark:text-slate-300 leading-relaxed">
                    {summary.riskExplanation}
                  </p>
                </div>

                {/* Next Steps / Mitigations list */}
                <div className="space-y-3">
                  <h5 className="text-xs font-bold text-slate-800 dark:text-slate-100 font-mono uppercase tracking-wider">
                    🛡️ Recommended Mitigation Next Steps
                  </h5>
                  <div className="grid grid-cols-1 gap-2.5">
                    {summary.mitigationSteps.map((step, idx) => (
                      <div 
                        key={idx}
                        className="flex items-start gap-3 p-3 bg-white dark:bg-[#161920]/20 border border-slate-100 dark:border-white/5 rounded-xl text-xs"
                      >
                        <span className="w-5 h-5 bg-emerald-500/10 text-emerald-500 text-[10px] font-mono font-bold flex items-center justify-center rounded-full shrink-0 mt-0.5">
                          {idx + 1}
                        </span>
                        <p className="text-slate-600 dark:text-slate-300 font-medium">
                          {step}
                        </p>
                      </div>
                    ))}
                  </div>
                </div>
              </div>
            )}

            {/* CORE OBLIGATIONS PANEL */}
            {activeSection === 'obligations' && (
              <div className="space-y-6 animate-fade-in">
                <div>
                  <h5 className="text-sm font-bold text-slate-800 dark:text-slate-100 flex items-center gap-1.5 font-mono">
                    📋 Key Obligations & Action Items
                  </h5>
                  <p className="text-[11px] text-slate-400 dark:text-slate-500 mt-0.5">
                    Extracted lists of actions, deliverables, and performance duties mandated for each party.
                  </p>
                </div>

                <div className="grid grid-cols-1 gap-3">
                  {summary.coreObligations.map((obl, idx) => (
                    <div 
                      key={idx}
                      className="p-4 bg-slate-50/50 dark:bg-[#161920]/40 border border-slate-100 dark:border-white/5 rounded-2xl flex items-start gap-3.5 text-xs transition-all hover:bg-slate-50 dark:hover:bg-[#161920]/60"
                    >
                      <div className="p-1.5 bg-emerald-500/10 text-emerald-500 rounded-lg shrink-0 mt-0.5">
                        <CheckCircle className="w-3.5 h-3.5 text-emerald-500" />
                      </div>
                      <p className="text-slate-700 dark:text-slate-200 leading-relaxed font-sans">
                        {obl}
                      </p>
                    </div>
                  ))}
                </div>
              </div>
            )}

            {/* COMMERCIALS PANEL */}
            {activeSection === 'commercials' && (
              <div className="space-y-6 animate-fade-in">
                <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                  {/* Payment & pricing terms */}
                  <div className="space-y-4">
                    <div>
                      <h5 className="text-xs font-bold text-slate-800 dark:text-slate-100 flex items-center gap-1.5 font-mono uppercase tracking-wider">
                        💵 Commercial & Pricing Terms
                      </h5>
                      <p className="text-[11px] text-slate-400 dark:text-slate-500 mt-0.5">
                        Invoicing details, payout schedules, rates, and penalty metrics located inside the document text.
                      </p>
                    </div>

                    <div className="space-y-2.5">
                      {summary.paymentTerms.map((term, idx) => (
                        <div 
                          key={idx}
                          className="p-3 bg-emerald-500/[0.02] border border-emerald-500/10 dark:border-emerald-500/5 rounded-xl text-xs flex items-start gap-2.5"
                        >
                          <span className="text-emerald-500 font-bold mt-0.5">$</span>
                          <p className="text-slate-600 dark:text-slate-300">
                            {term}
                          </p>
                        </div>
                      ))}
                    </div>
                  </div>

                  {/* Deadlines & milestones */}
                  <div className="space-y-4">
                    <div>
                      <h5 className="text-xs font-bold text-slate-800 dark:text-slate-100 flex items-center gap-1.5 font-mono uppercase tracking-wider">
                        📅 Key Milestones & Dates
                      </h5>
                      <p className="text-[11px] text-slate-400 dark:text-slate-500 mt-0.5">
                        Required delivery dates, termination notices, expiration windows, and timeline commitments.
                      </p>
                    </div>

                    <div className="space-y-2.5">
                      {summary.keyDeadlines.map((dl, idx) => (
                        <div 
                          key={idx}
                          className="p-3 bg-blue-500/[0.02] border border-blue-500/10 dark:border-blue-500/5 rounded-xl text-xs flex items-start gap-2.5"
                        >
                          <Calendar className="w-4 h-4 text-blue-500 shrink-0 mt-0.5" />
                          <p className="text-slate-600 dark:text-slate-300">
                            {dl}
                          </p>
                        </div>
                      ))}
                    </div>
                  </div>
                </div>
              </div>
            )}

            {/* RISK CLAUSES PANEL */}
            {activeSection === 'risks' && (
              <div className="space-y-6 animate-fade-in">
                <div>
                  <h5 className="text-sm font-bold text-slate-800 dark:text-slate-100 flex items-center gap-1.5 font-mono">
                    ⚠️ Detected Risk Clauses & Recommended Adjustments
                  </h5>
                  <p className="text-[11px] text-slate-400 dark:text-slate-500 mt-0.5">
                    Indemnification loops, auto-renewals, non-standard liabilities, and high risk sections requiring mitigation.
                  </p>
                </div>

                <div className="grid grid-cols-1 gap-4">
                  {summary.riskClauses.map((rc, idx) => (
                    <div 
                      key={idx}
                      className="p-4 bg-slate-50/50 dark:bg-[#161920]/40 border border-slate-100 dark:border-white/5 rounded-2xl space-y-3"
                    >
                      <div className="flex items-center justify-between gap-4">
                        <span className="font-bold text-slate-800 dark:text-slate-200 text-xs flex items-center gap-2">
                          <span className="w-5 h-5 bg-slate-200 dark:bg-slate-800 text-slate-500 text-[10px] font-mono font-bold flex items-center justify-center rounded-full shrink-0">
                            {idx + 1}
                          </span>
                          {rc.clauseName}
                        </span>

                        <span className={`px-2 py-0.5 text-[9px] font-mono uppercase font-bold rounded-md border ${
                          rc.severity === 'High' 
                            ? 'bg-rose-500/10 text-rose-500 border-rose-500/20' 
                            : rc.severity === 'Medium'
                              ? 'bg-amber-500/10 text-amber-500 border-amber-500/20'
                              : 'bg-emerald-500/10 text-emerald-500 border-emerald-500/20'
                        }`}>
                          {rc.severity} severity
                        </span>
                      </div>

                      <div className="pl-7 space-y-2.5">
                        <p className="text-xs text-slate-500 dark:text-slate-400 leading-normal">
                          <strong className="text-slate-600 dark:text-slate-300">Clause Content:</strong> {rc.description}
                        </p>
                        
                        <div className="p-3 bg-amber-500/[0.02] border border-amber-500/10 dark:border-amber-500/5 rounded-xl text-xs flex items-start gap-2 text-slate-600 dark:text-slate-300">
                          <ChevronRight className="w-4 h-4 text-amber-500 shrink-0 mt-0.5" />
                          <p>
                            <strong className="text-amber-600 dark:text-amber-400 font-mono text-[10px] uppercase font-bold tracking-wider block mb-0.5">Recommended mitigation action:</strong>
                            {rc.recommendation}
                          </p>
                        </div>
                      </div>
                    </div>
                  ))}
                </div>
              </div>
            )}

          </div>
        </div>
      )}

    </div>
  );
}
