import { useState, useEffect } from 'react';
import { 
  Sparkles, 
  BookOpen, 
  Trophy, 
  Check, 
  X, 
  ChevronRight, 
  ChevronLeft, 
  RefreshCw, 
  FileText, 
  Layers, 
  Download,
  AlertCircle
} from 'lucide-react';
import { FileItem } from '../types';

interface AIStudyToolProps {
  fileItem: FileItem;
  onReset: () => void;
}

interface QuizQuestion {
  question: string;
  options: string[];
  correctIndex: number;
  explanation: string;
}

interface Flashcard {
  term: string;
  definition: string;
}

export default function AIStudyTool({ fileItem, onReset }: AIStudyToolProps) {
  const [activeTab, setActiveTab] = useState<'guide' | 'quiz' | 'flashcards'>('guide');
  const [isGenerating, setIsGenerating] = useState<boolean>(true);
  const [errorMessage, setErrorMessage] = useState<string | null>(null);

  // Content states
  const [studyGuide, setStudyGuide] = useState<string>('');
  const [quizQuestions, setQuizQuestions] = useState<QuizQuestion[]>([]);
  const [flashcards, setFlashcards] = useState<Flashcard[]>([]);

  // Interactive Quiz states
  const [quizAnswers, setQuizAnswers] = useState<Record<number, number>>({});
  const [showScore, setShowScore] = useState<boolean>(false);

  // Interactive Flashcards states
  const [currentCardIndex, setCurrentCardIndex] = useState<number>(0);
  const [isFlipped, setIsFlipped] = useState<boolean>(false);

  useEffect(() => {
    generateStudyPack();
  }, [fileItem.id]);

  const generateStudyPack = async () => {
    setIsGenerating(true);
    setErrorMessage(null);
    setStudyGuide('');
    setQuizQuestions([]);
    setFlashcards([]);
    setQuizAnswers({});
    setShowScore(false);
    setCurrentCardIndex(0);
    setIsFlipped(false);

    const formData = new FormData();
    formData.append('file', fileItem.file);

    try {
      const response = await fetch('/api/convert/ai-study', {
        method: 'POST',
        body: formData
      });

      if (!response.ok) {
        const errText = await response.text();
        throw new Error(errText || 'Could not generate study materials from this document.');
      }

      const data = await response.json();
      if (data.success) {
        setStudyGuide(data.studyGuide || '');
        setQuizQuestions(data.quizQuestions || []);
        setFlashcards(data.flashcards || []);
      } else {
        throw new Error(data.error || 'Server failed to build study companion pack.');
      }
    } catch (err: any) {
      console.error('Study pack error:', err);
      setErrorMessage(err.message || 'Failed to analyze this document. Ensure it contains readable text.');
    } finally {
      setIsGenerating(false);
    }
  };

  const handleSelectOption = (questionIndex: number, optionIndex: number) => {
    if (showScore) return; // quiz completed
    setQuizAnswers(prev => ({
      ...prev,
      [questionIndex]: optionIndex
    }));
  };

  const getScore = () => {
    let score = 0;
    quizQuestions.forEach((q, idx) => {
      if (quizAnswers[idx] === q.correctIndex) {
        score++;
      }
    });
    return score;
  };

  const handleDownloadStudyPack = () => {
    let textContent = `==================================================\n`;
    textContent += `STUDY COMPANION PACK: ${fileItem.name}\n`;
    textContent += `Generated by PDF PRO on ${new Date().toLocaleDateString()}\n`;
    textContent += `==================================================\n\n`;

    textContent += `--------------------------------------------------\n`;
    textContent += `PART 1: SYSTEMATIC STUDY GUIDE & KEY CONCEPTS\n`;
    textContent += `--------------------------------------------------\n\n`;
    textContent += studyGuide + `\n\n`;

    textContent += `--------------------------------------------------\n`;
    textContent += `PART 2: ACTIVE-RECALL FLASHCARDS\n`;
    textContent += `--------------------------------------------------\n\n`;
    flashcards.forEach((card, idx) => {
      textContent += `Flashcard [${idx + 1}/${flashcards.length}]\n`;
      textContent += `TERM/CONCEPT: ${card.term}\n`;
      textContent += `DEFINITION:   ${card.definition}\n`;
      textContent += `--------------------------------------------------\n`;
    });
    textContent += `\n`;

    textContent += `--------------------------------------------------\n`;
    textContent += `PART 3: PRACTICE ASSESSMENTS (QUIZ)\n`;
    textContent += `--------------------------------------------------\n\n`;
    quizQuestions.forEach((q, idx) => {
      textContent += `Question ${idx + 1}: ${q.question}\n`;
      q.options.forEach((opt, oIdx) => {
        textContent += `  [${String.fromCharCode(65 + oIdx)}] ${opt}\n`;
      });
      textContent += `Correct Answer: [${String.fromCharCode(65 + q.correctIndex)}] ${q.options[q.correctIndex]}\n`;
      textContent += `Explanation: ${q.explanation}\n`;
      textContent += `--------------------------------------------------\n`;
    });

    const blob = new Blob([textContent], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `${fileItem.name.replace(/\.[^/.]+$/, "")}-Study-Pack.txt`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="bg-white dark:bg-[#12151C] border border-slate-100 dark:border-white/5 rounded-3xl overflow-hidden shadow-sm flex flex-col min-h-[580px]">
      
      {/* HEADER SECTION */}
      <div className="px-6 py-5 bg-slate-50 dark:bg-[#161920]/60 border-b border-slate-100 dark:border-white/5 flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div className="flex items-center space-x-3.5">
          <div className="p-2.5 bg-rose-500/10 text-rose-500 rounded-2xl shadow-sm">
            <BookOpen className="w-5 h-5 text-red-500" />
          </div>
          <div>
            <h4 className="font-display font-bold text-slate-800 dark:text-slate-100 text-base flex items-center gap-2">
              AI Study & Quiz Partner
              <span className="text-[10px] font-mono uppercase bg-red-500/10 text-red-600 dark:text-red-400 px-2 py-0.5 rounded font-bold">
                PRO ACTIVE
              </span>
            </h4>
            <p className="text-xs text-slate-400 dark:text-slate-500 max-w-sm truncate mt-0.5">
              Analyzing: {fileItem.name} ({Math.round(fileItem.size / 1024)} KB)
            </p>
          </div>
        </div>

        <div className="flex items-center gap-2">
          {!isGenerating && !errorMessage && (
            <button
              onClick={handleDownloadStudyPack}
              className="px-3.5 py-2 bg-slate-100 hover:bg-slate-200 dark:bg-white/5 dark:hover:bg-white/10 text-slate-700 dark:text-slate-200 rounded-xl text-xs font-bold flex items-center gap-1.5 transition-all cursor-pointer font-sans"
              title="Download full Study Pack offline"
            >
              <Download className="w-4 h-4 text-rose-500" />
              <span>Download study pack</span>
            </button>
          )}
          <button
            onClick={generateStudyPack}
            disabled={isGenerating}
            className="p-2 hover:bg-slate-200 dark:hover:bg-[#161920] rounded-xl text-slate-400 hover:text-slate-600 dark:hover:text-slate-300 transition-colors cursor-pointer"
            title="Re-analyze and regenerate"
          >
            <RefreshCw className={`w-4 h-4 ${isGenerating ? 'animate-spin text-rose-500' : ''}`} />
          </button>
          <button
            onClick={onReset}
            disabled={isGenerating}
            className="p-2 hover:bg-slate-200 dark:hover:bg-[#161920] rounded-xl text-slate-400 hover:text-slate-600 dark:hover:text-slate-300 transition-colors cursor-pointer text-xs font-semibold px-3 border border-slate-100 dark:border-white/5"
          >
            Close
          </button>
        </div>
      </div>

      {/* GENERATING LOADING SCREEN */}
      {isGenerating && (
        <div className="flex-1 flex flex-col items-center justify-center p-8 text-center space-y-6 animate-fade-in my-12">
          <div className="relative">
            <div className="w-16 h-16 rounded-full border-4 border-red-500/10 border-t-red-500 animate-spin"></div>
            <div className="absolute inset-0 flex items-center justify-center">
              <Sparkles className="w-6 h-6 text-red-500 animate-pulse" />
            </div>
          </div>
          <div className="space-y-2 max-w-md">
            <h5 className="font-display font-bold text-slate-800 dark:text-slate-100 text-lg">
              Synthesizing Academic Materials...
            </h5>
            <p className="text-xs text-slate-400 leading-relaxed font-mono">
              Parsing sections, isolating core vocabulary, constructing multiple-choice assessments, and building active-recall cards using Gemini...
            </p>
          </div>
        </div>
      )}

      {/* ERROR SCREEN */}
      {!isGenerating && errorMessage && (
        <div className="flex-1 flex flex-col items-center justify-center p-8 text-center space-y-4 my-12">
          <div className="p-4 bg-rose-500/10 text-rose-500 rounded-full">
            <AlertCircle className="w-8 h-8" />
          </div>
          <div className="space-y-1 max-w-sm">
            <h5 className="font-display font-bold text-slate-800 dark:text-slate-100 text-base">
              Failed to Analyze Document
            </h5>
            <p className="text-xs text-slate-400 leading-relaxed">
              {errorMessage}
            </p>
          </div>
          <button
            onClick={generateStudyPack}
            className="px-4 py-2 bg-red-600 hover:bg-red-500 text-white text-xs font-bold rounded-xl shadow-md cursor-pointer transition-all font-sans"
          >
            Retry Analysis
          </button>
        </div>
      )}

      {/* COMPLETED TAB INTERFACE */}
      {!isGenerating && !errorMessage && (
        <div className="flex-1 flex flex-col">
          {/* TAB SWITCHER NAVBAR */}
          <div className="px-6 bg-slate-50/50 dark:bg-[#161920]/20 border-b border-slate-100 dark:border-white/5 flex space-x-1.5 p-2">
            <button
              onClick={() => setActiveTab('guide')}
              className={`px-4 py-2 text-xs font-bold rounded-xl transition-all cursor-pointer flex items-center gap-1.5 ${
                activeTab === 'guide'
                  ? 'bg-red-500 text-white shadow-sm shadow-red-500/10'
                  : 'text-slate-500 hover:text-slate-800 dark:text-slate-400 dark:hover:text-slate-200 hover:bg-slate-100 dark:hover:bg-white/5'
              }`}
            >
              <FileText className="w-3.5 h-3.5" />
              Study Guide
            </button>
            <button
              onClick={() => setActiveTab('quiz')}
              className={`px-4 py-2 text-xs font-bold rounded-xl transition-all cursor-pointer flex items-center gap-1.5 ${
                activeTab === 'quiz'
                  ? 'bg-red-500 text-white shadow-sm shadow-red-500/10'
                  : 'text-slate-500 hover:text-slate-800 dark:text-slate-400 dark:hover:text-slate-200 hover:bg-slate-100 dark:hover:bg-white/5'
              }`}
            >
              <Trophy className="w-3.5 h-3.5" />
              Practice Quiz
              {quizQuestions.length > 0 && (
                <span className="text-[9px] px-1.5 py-0.5 bg-white/20 text-white rounded font-mono font-bold">
                  {quizQuestions.length}
                </span>
              )}
            </button>
            <button
              onClick={() => setActiveTab('flashcards')}
              className={`px-4 py-2 text-xs font-bold rounded-xl transition-all cursor-pointer flex items-center gap-1.5 ${
                activeTab === 'flashcards'
                  ? 'bg-red-500 text-white shadow-sm shadow-red-500/10'
                  : 'text-slate-500 hover:text-slate-800 dark:text-slate-400 dark:hover:text-slate-200 hover:bg-slate-100 dark:hover:bg-white/5'
              }`}
            >
              <Layers className="w-3.5 h-3.5" />
              Flashcards
              {flashcards.length > 0 && (
                <span className="text-[9px] px-1.5 py-0.5 bg-white/20 text-white rounded font-mono font-bold">
                  {flashcards.length}
                </span>
              )}
            </button>
          </div>

          {/* TAB CONTENTS */}
          <div className="flex-1 p-6 overflow-y-auto">
            
            {/* STUDY GUIDE TAB */}
            {activeTab === 'guide' && (
              <div className="space-y-6 animate-fade-in">
                <div className="flex items-center justify-between">
                  <h5 className="text-sm font-bold text-slate-800 dark:text-slate-100 flex items-center gap-1.5 font-mono">
                    🎓 Key Outline & Summary Guide
                  </h5>
                  <span className="text-[10px] font-mono text-slate-400 dark:text-slate-500 uppercase tracking-widest bg-slate-50 dark:bg-[#0A0B0E] px-2.5 py-1 rounded border border-slate-100 dark:border-white/5">
                    Structure preserved
                  </span>
                </div>
                
                <div className="prose prose-slate dark:prose-invert max-w-none text-slate-600 dark:text-slate-300 text-xs leading-relaxed space-y-4 whitespace-pre-line font-sans border border-slate-100 dark:border-white/5 p-5 rounded-2xl bg-slate-50/50 dark:bg-[#12151C]/60">
                  {studyGuide || "No structured guide returned. Try to re-analyze."}
                </div>
              </div>
            )}

            {/* PRACTICE QUIZ TAB */}
            {activeTab === 'quiz' && (
              <div className="space-y-6 animate-fade-in">
                <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 pb-2 border-b border-slate-100 dark:border-white/5">
                  <div>
                    <h5 className="text-sm font-bold text-slate-800 dark:text-slate-100 flex items-center gap-1.5 font-mono">
                      🏆 Self-Assessment Practice Quiz
                    </h5>
                    <p className="text-[11px] text-slate-400 dark:text-slate-500 mt-0.5">
                      Check your knowledge on key topics covered inside the document.
                    </p>
                  </div>
                  
                  {quizQuestions.length > 0 && !showScore && (
                    <button
                      onClick={() => setShowScore(true)}
                      disabled={Object.keys(quizAnswers).length === 0}
                      className="px-4 py-2 bg-gradient-to-r from-red-600 to-rose-600 hover:from-red-500 hover:to-rose-500 disabled:from-slate-200 disabled:to-slate-300 disabled:dark:from-slate-800 disabled:dark:to-slate-900 text-white font-bold text-xs rounded-xl shadow-md cursor-pointer transition-all font-sans shrink-0"
                    >
                      Submit Answers ({Object.keys(quizAnswers).length}/{quizQuestions.length})
                    </button>
                  )}
                </div>

                {/* Score Summary Banner */}
                {showScore && (
                  <div className="p-6 bg-gradient-to-br from-emerald-500/10 to-teal-500/10 border border-emerald-500/20 rounded-2xl flex flex-col md:flex-row md:items-center justify-between gap-5 animate-scale-up">
                    <div className="flex items-center space-x-4">
                      <div className="p-3.5 bg-emerald-500 text-white rounded-2xl shadow-lg shadow-emerald-500/15">
                        <Trophy className="w-7 h-7" />
                      </div>
                      <div>
                        <h4 className="font-display font-bold text-slate-800 dark:text-slate-100 text-lg">
                          Quiz Assessment Complete!
                        </h4>
                        <p className="text-xs text-slate-500 dark:text-slate-400 mt-0.5 leading-relaxed">
                          Great job checking your retention. Review individual answer explanations below to clarify concepts.
                        </p>
                      </div>
                    </div>
                    
                    <div className="flex items-center gap-4 shrink-0">
                      <div className="text-right">
                        <span className="text-[10px] uppercase font-bold tracking-widest text-slate-400 block font-mono">Your Score</span>
                        <span className="text-2xl font-black text-emerald-600 dark:text-emerald-400 font-mono">
                          {getScore()} <span className="text-slate-400 font-light">/ {quizQuestions.length}</span>
                        </span>
                        <span className="text-xs font-bold text-emerald-500 block">
                          ({Math.round((getScore() / quizQuestions.length) * 100)}% accuracy)
                        </span>
                      </div>
                      <button
                        onClick={() => {
                          setQuizAnswers({});
                          setShowScore(false);
                        }}
                        className="p-3 bg-white dark:bg-[#12151C] border border-slate-200 dark:border-white/10 hover:border-red-500 rounded-xl text-slate-600 dark:text-slate-300 hover:text-red-500 transition-colors cursor-pointer"
                        title="Retry Quiz"
                      >
                        <RefreshCw className="w-4 h-4" />
                      </button>
                    </div>
                  </div>
                )}

                {/* Questions List */}
                <div className="space-y-6">
                  {quizQuestions.length === 0 ? (
                    <p className="text-center text-slate-400 font-mono py-8">No quiz questions generated.</p>
                  ) : (
                    quizQuestions.map((q, idx) => {
                      const selectedOpt = quizAnswers[idx];
                      const isCorrect = selectedOpt === q.correctIndex;
                      
                      return (
                        <div 
                          key={idx} 
                          className={`p-5 rounded-2xl border transition-all duration-300 space-y-4 ${
                            showScore 
                              ? isCorrect 
                                ? 'bg-emerald-500/[0.02] border-emerald-500/30 dark:border-emerald-500/20'
                                : 'bg-rose-500/[0.02] border-rose-500/30 dark:border-rose-500/20'
                              : 'bg-slate-50/50 dark:bg-[#161920]/40 border-slate-100 dark:border-white/5'
                          }`}
                        >
                          <div className="flex items-start gap-3">
                            <span className="w-5 h-5 bg-red-50 dark:bg-red-950/30 text-red-600 dark:text-red-400 text-xs font-bold flex items-center justify-center rounded-full shrink-0 mt-0.5 font-mono">
                              {idx + 1}
                            </span>
                            <h6 className="text-xs font-bold text-slate-800 dark:text-slate-200 leading-normal">
                              {q.question}
                            </h6>
                          </div>

                          <div className="grid grid-cols-1 gap-2.5 pl-8">
                            {q.options.map((opt, oIdx) => {
                              const isThisSelected = selectedOpt === oIdx;
                              const isThisCorrectAnswer = q.correctIndex === oIdx;
                              
                              let buttonStyle = 'bg-white dark:bg-[#12151C] border-slate-200 dark:border-white/10 text-slate-700 dark:text-slate-300 hover:border-red-500/50 dark:hover:border-red-500/30';
                              
                              if (showScore) {
                                if (isThisCorrectAnswer) {
                                  buttonStyle = 'bg-emerald-500/10 border-emerald-500/50 text-emerald-700 dark:text-emerald-400 font-bold';
                                } else if (isThisSelected) {
                                  buttonStyle = 'bg-rose-500/10 border-rose-500/50 text-rose-700 dark:text-rose-400 font-bold';
                                } else {
                                  buttonStyle = 'bg-slate-50 dark:bg-[#0A0B0E]/30 border-slate-200 dark:border-white/5 text-slate-400 dark:text-slate-500 opacity-60';
                                }
                              } else if (isThisSelected) {
                                buttonStyle = 'bg-red-500/5 dark:bg-red-500/10 border-red-500 text-red-600 dark:text-red-400 font-bold ring-2 ring-red-500/10';
                              }

                              return (
                                <button
                                  key={oIdx}
                                  onClick={() => handleSelectOption(idx, oIdx)}
                                  disabled={showScore}
                                  className={`p-3 rounded-xl border text-left text-xs transition-all flex items-center justify-between gap-3 ${buttonStyle} ${!showScore ? 'cursor-pointer' : 'cursor-default'}`}
                                >
                                  <span className="flex items-center gap-2">
                                    <span className="text-[10px] font-mono font-bold text-slate-400 dark:text-slate-500">
                                      {String.fromCharCode(65 + oIdx)}.
                                    </span>
                                    <span>{opt}</span>
                                  </span>

                                  {/* feedback status icon */}
                                  {showScore && isThisCorrectAnswer && (
                                    <Check className="w-4 h-4 text-emerald-500 shrink-0" />
                                  )}
                                  {showScore && isThisSelected && !isThisCorrectAnswer && (
                                    <X className="w-4 h-4 text-rose-500 shrink-0" />
                                  )}
                                </button>
                              );
                            })}
                          </div>

                          {/* Interactive explanation box */}
                          {showScore && (
                            <div className={`mt-3 p-3 rounded-xl border pl-8 text-xs leading-relaxed space-y-1 animate-fade-in ${
                              isCorrect 
                                ? 'bg-emerald-500/[0.01] border-emerald-500/10 text-slate-600 dark:text-slate-300' 
                                : 'bg-rose-500/[0.01] border-rose-500/10 text-slate-600 dark:text-slate-300'
                            }`}>
                              <span className={`font-bold flex items-center gap-1 font-mono uppercase text-[9px] tracking-wider ${isCorrect ? 'text-emerald-600 dark:text-emerald-400' : 'text-rose-600 dark:text-rose-400'}`}>
                                {isCorrect ? '✓ Correct Explanation' : '✗ Answer Clarification'}
                              </span>
                              <p className="font-sans font-medium">{q.explanation}</p>
                            </div>
                          )}
                        </div>
                      );
                    })
                  )}
                </div>
              </div>
            )}

            {/* ACTIVE-RECALL FLASHCARDS TAB */}
            {activeTab === 'flashcards' && (
              <div className="space-y-6 animate-fade-in">
                <div className="text-center max-w-sm mx-auto space-y-1">
                  <h5 className="text-sm font-bold text-slate-800 dark:text-slate-100 flex items-center justify-center gap-1.5 font-mono">
                    📇 Active-Recall Flashcards
                  </h5>
                  <p className="text-[11px] text-slate-400 dark:text-slate-500 leading-normal">
                    Test your recall. Read the concept, think of the definition, then click to flip the card.
                  </p>
                </div>

                {flashcards.length === 0 ? (
                  <p className="text-center text-slate-400 font-mono py-8">No flashcards generated.</p>
                ) : (
                  <div className="flex flex-col items-center justify-center space-y-6 py-4">
                    {/* Card Container */}
                    <div 
                      onClick={() => setIsFlipped(!isFlipped)}
                      className="w-full max-w-md h-56 perspective cursor-pointer group"
                    >
                      <div className={`relative w-full h-full duration-500 transform-style-3d transition-transform ${isFlipped ? 'rotate-y-180' : ''}`}>
                        {/* Front Side */}
                        <div className="absolute inset-0 backface-hidden bg-slate-50 dark:bg-[#161920] border-2 border-slate-200/50 dark:border-white/5 rounded-3xl p-6 flex flex-col justify-between shadow-md group-hover:border-red-500/40 transition-colors">
                          <span className="text-[10px] font-mono uppercase font-bold text-slate-400 tracking-wider">
                            Active Card Front [ {currentCardIndex + 1} / {flashcards.length} ]
                          </span>
                          
                          <div className="text-center px-4 space-y-1.5">
                            <span className="inline-block p-2 bg-red-500/10 text-red-500 rounded-xl">
                              <Sparkles className="w-4 h-4 fill-current text-red-500" />
                            </span>
                            <h4 className="font-display font-bold text-slate-800 dark:text-slate-100 text-lg tracking-tight">
                              {flashcards[currentCardIndex]?.term}
                            </h4>
                          </div>

                          <span className="text-[10px] font-mono text-slate-400 font-bold text-center block uppercase tracking-widest animate-pulse">
                            🖱️ Click card to Flip
                          </span>
                        </div>

                        {/* Back Side */}
                        <div className="absolute inset-0 backface-hidden rotate-y-180 bg-gradient-to-br from-red-500/5 to-rose-600/5 dark:from-red-950/10 dark:to-rose-950/10 border-2 border-red-500/20 dark:border-red-500/10 rounded-3xl p-6 flex flex-col justify-between shadow-md">
                          <span className="text-[10px] font-mono uppercase font-bold text-red-500 dark:text-red-400 tracking-wider">
                            Card Definition Back [ {currentCardIndex + 1} / {flashcards.length} ]
                          </span>
                          
                          <div className="text-center px-4">
                            <p className="text-xs text-slate-700 dark:text-slate-200 leading-relaxed font-sans font-medium">
                              {flashcards[currentCardIndex]?.definition}
                            </p>
                          </div>

                          <span className="text-[10px] font-mono text-slate-400 font-bold text-center block uppercase tracking-widest">
                            🖱️ Click to turn back
                          </span>
                        </div>
                      </div>
                    </div>

                    {/* Navigation Buttons */}
                    <div className="flex items-center space-x-6">
                      <button
                        onClick={() => {
                          setIsFlipped(false);
                          setCurrentCardIndex(prev => Math.max(0, prev - 1));
                        }}
                        disabled={currentCardIndex === 0}
                        className="p-3 bg-slate-100 hover:bg-slate-200 dark:bg-white/5 dark:hover:bg-white/10 disabled:opacity-40 text-slate-600 dark:text-slate-300 rounded-xl transition-all cursor-pointer flex items-center justify-center border border-slate-100 dark:border-white/5"
                        title="Previous Card"
                      >
                        <ChevronLeft className="w-5 h-5" />
                      </button>

                      <span className="text-xs font-mono font-bold text-slate-500">
                        {currentCardIndex + 1} <span className="text-slate-300 dark:text-slate-700">/</span> {flashcards.length}
                      </span>

                      <button
                        onClick={() => {
                          setIsFlipped(false);
                          setCurrentCardIndex(prev => Math.min(flashcards.length - 1, prev + 1));
                        }}
                        disabled={currentCardIndex === flashcards.length - 1}
                        className="p-3 bg-slate-100 hover:bg-slate-200 dark:bg-white/5 dark:hover:bg-white/10 disabled:opacity-40 text-slate-600 dark:text-slate-300 rounded-xl transition-all cursor-pointer flex items-center justify-center border border-slate-100 dark:border-white/5"
                        title="Next Card"
                      >
                        <ChevronRight className="w-5 h-5" />
                      </button>
                    </div>
                  </div>
                )}
              </div>
            )}

          </div>
        </div>
      )}

    </div>
  );
}
